// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIxQnjPtFr80NxWKDN5QtPtLL7nqEEvFM',
    appId: '1:1075344531602:web:957d8007debb5a75e1c64b',
    messagingSenderId: '1075344531602',
    projectId: 'flutterapp-8031f',
    authDomain: 'flutterapp-8031f.firebaseapp.com',
    storageBucket: 'flutterapp-8031f.appspot.com',
    measurementId: 'G-5MZJ3X4F31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-IBSGmiN-xzYScDQxvUkfCE2PjiP4QL4',
    appId: '1:1075344531602:android:841fd97b7af883b6e1c64b',
    messagingSenderId: '1075344531602',
    projectId: 'flutterapp-8031f',
    storageBucket: 'flutterapp-8031f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9qmcwedDJB_s1I37zHn2M5CSfp2ndtUw',
    appId: '1:1075344531602:ios:ab5862a56f8159eee1c64b',
    messagingSenderId: '1075344531602',
    projectId: 'flutterapp-8031f',
    storageBucket: 'flutterapp-8031f.appspot.com',
    iosBundleId: 'com.example.phoneOtpUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9qmcwedDJB_s1I37zHn2M5CSfp2ndtUw',
    appId: '1:1075344531602:ios:67be99f8858f54a4e1c64b',
    messagingSenderId: '1075344531602',
    projectId: 'flutterapp-8031f',
    storageBucket: 'flutterapp-8031f.appspot.com',
    iosBundleId: 'com.example.phonenumber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIxQnjPtFr80NxWKDN5QtPtLL7nqEEvFM',
    appId: '1:1075344531602:web:e042f143f782a2b6e1c64b',
    messagingSenderId: '1075344531602',
    projectId: 'flutterapp-8031f',
    authDomain: 'flutterapp-8031f.firebaseapp.com',
    storageBucket: 'flutterapp-8031f.appspot.com',
    measurementId: 'G-LWCXCTQM76',
  );
}
